In [113]:
import numpy as np
import scipy

In [18]:
n, f, k = 2, 5, 3

In [59]:
x = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9]], dtype=np.float32)
y = np.array([0,2])

In [60]:
x, y

(array([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]], dtype=float32),
 array([0, 2]))

In [61]:
X = np.zeros((n*k,k*f))
for i in range(n):
    for j in range(k):
        X[i*k + j, j*f:j*f+f] = x[i,:]

In [62]:
X

array([[0., 1., 2., 3., 4., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 2., 3., 4., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 5., 6., 7., 8., 9., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 5., 6., 7., 8., 9.]])

In [69]:
Y = np.zeros((n,k))
Y[np.arange(n),y] = 1
Y = Y.reshape((n*k,))

In [70]:
Y

array([1., 0., 0., 0., 0., 1.])

In [115]:
c = np.concat([np.ones(n*k), np.zeros(f*k)])

In [96]:
A_ub = np.concat([
    np.concat([-X,               -np.eye(n*k)],        axis=1),
    np.concat([ X,               -np.eye(n*k)],        axis=1),
    np.concat([-X,               np.zeros((n*k,n*k))], axis=1),
    np.concat([np.zeros_like(X), -np.eye(n*k)],        axis=1),
], axis=0)

In [99]:
A_ub.shape, (4*n*k, k*f+n*k)

((24, 21), (24, 21))

In [108]:
b_ub = np.concat([
    -Y,
    Y,
    np.zeros_like(Y),
    np.zeros_like(Y)
], axis=0)

In [109]:
b_ub.shape

(24,)

In [118]:
one_mat = np.repeat(np.eye(n), k, axis=1)
A_eq = np.concat([
    one_mat@X, np.zeros((n,n*k))
], axis=1)
b_eq = np.ones(n)

In [119]:
one_mat

array([[1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1.]])

In [110]:
A_eq.shape

(2, 15)

In [116]:
c

array([1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.])

In [123]:
res = scipy.optimize.linprog(c, A_ub, b_ub, A_eq, b_eq)

In [124]:
res

       message: The problem is infeasible. (HiGHS Status 8: model_status is Infeasible; primal_status is At lower/fixed bound)
       success: False
        status: 2
           fun: None
             x: None
           nit: 2
         lower:  residual: None
                marginals: None
         upper:  residual: None
                marginals: None
         eqlin:  residual: None
                marginals: None
       ineqlin:  residual: None
                marginals: None